package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2020-APR-15  02:19:49 PM
 */
public class Phraseswt_prompt extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(26);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: welcome
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "welcome", "welcome.wav", ""); 

		// phrase: noinput
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noinput", "noinput.wav", ""); 

		// phrase: transfer
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "transfer", "transfer.wav", ""); 

		// phrase: ENG-FORPREPAID
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ENG-FORPREPAID", "ENG-FORPREPAID.wav", ""); 

		// phrase: PRESS1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PRESS1", "PRESS1.wav", ""); 

		// phrase: ENG-FORPOSTPAID
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ENG-FORPOSTPAID", "ENG-FORPOSTPAID.wav", ""); 

		// phrase: PRESS2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PRESS2", "PRESS2.wav", ""); 

		// phrase: ENG-FOR-DTH
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ENG-FOR-DTH", "ENG-FOR-DTH.wav", ""); 

		// phrase: PRESS3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PRESS3", "PRESS3.wav", ""); 

		// phrase: ENG-FIXLINE-BROADBAND
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ENG-FIXLINE-BROADBAND", "ENG-FIXLINE-BROADBAND.wav", ""); 

		// phrase: PRESS4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PRESS4", "PRESS4.wav", ""); 

		// phrase: ENG-FOR-AIRTELMONEY
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ENG-FOR-AIRTELMONEY", "ENG-FOR-AIRTELMONEY.wav", ""); 

		// phrase: PRESS5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PRESS5", "PRESS5.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2020-APR-15  10:41:08 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(Phraseswt_prompt.PHRASE_MAP, phraseName));
	}
}
